"""add estimated_time to Problem, Task, Subtask

Revision ID: 66523447255c
Revises: 5146c1048f9d
Create Date: 2026-05-30 19:29:59.116412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66523447255c'
down_revision = '5146c1048f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###
